language: python
python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=zeny_plugin.settings_travis

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - wget https://raw.githubusercontent.com/rathena/rathena/master/db/re/item_trade.txt

# command to run tests
script: python manage.py test
